name: Build
on: 
  push
  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.20'

      - run: go version

      - name: Test
        run: go test ./...
      - name: Build
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: go build

      - name: Upload build artifcat
        uses: actions/upload-artifact@v2
        with:
          name: binary
          path: helloActions

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifcat
        uses: actions/download-artifact@v2
        with:
          name: binary
          path: helloActions
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: helloActions
          automatic_release_tag: true
          files: helloActions